backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.json"
        fields:
          - label: "Galery"
            name: galery
            widget: "list"
            types:
              - label: "Image"
                name: "image"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - name: kategorie
                    label: "Filter"
                    widget: "select"
                    multiple: true
                    options: ["Zeit", "Zeitung", "Zeiger", "Zeneggen", "Uhr", "Testen", "Sammeln", "Schatten", "Schreiben", "Sonne", "Struggle", "Recherchieren", "Projizieren", "Natur", "Notizen", "Miro", "Lesen", "Loading", "Kalender", "Gefundenes", "Endspurt", "Experimentieren", "Beobachten", "Ausstellen"]
                  - name: kalenderwoche
                    label: "KW"
                    widget: "select"
                    multiple: false
                    options: ["KW 6","KW 7","KW 8","KW 9","KW 10","KW 11","KW 12","KW 13","KW 14","KW 15","KW 16","KW 17","KW 18","KW 19","KW 20","KW 21","KW 22","KW 23"]
              - label: "Video"
                name: "video"
                widget: "object"
                fields:
                  - { label: "Videolink", name: "videolink", widget: "file" }
                  - name: kategorie
                    label: "Filter"
                    widget: "select"
                    multiple: true
                    options: ["Zeit", "Zeitung", "Zeiger", "Zeneggen", "Uhr", "Testen", "Sammeln", "Schatten", "Schreiben", "Sonne", "Struggle", "Recherchieren", "Projizieren", "Natur", "Notizen", "Miro", "Lesen", "Loading", "Kalender", "Gefundenes", "Endspurt", "Experimentieren", "Beobachten", "Ausstellen"]
                  - name: kalenderwoche
                    label: "KW"
                    widget: "select"
                    multiple: false
                    options: ["KW 6","KW 7","KW 8","KW 9","KW 10","KW 11","KW 12","KW 13","KW 14","KW 15","KW 16","KW 17","KW 18","KW 19","KW 20","KW 21","KW 22","KW 23"]
