backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.json"
        fields:
          # - { label: "Title", name: "title", widget: "string"}
          # - { label: "Publish Date", name: "date", widget: "datetime" }
          # - { label: "Body", name: "body", widget: "markdown"}
          # - label: 'Cats'
          #   name: "cats"
          #   widget: list
          #   fields:
          #     - { label: "Name", name: "name", widget: "string"}
          #     - { label: "Description", name: "description", widget: "text"}
          # - label: "Content"
          #   name: content
          #   widget: list
          #   allow_add: true
          #   fields:
          #   - name: image
          #     label: "Bild"
          #     widget: image
          #     required: true
          - label: "Galery"
            name: "galery"
            widget: "list"
            types:
              - label: "Image"
                name: "image"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - name: kategorie
                    label: "Kategorie"
                    widget: "select"
                    multiple: false
                    options: ["Filter 1", "Filter 2", "Filter 3"]
              - label: "Video"
                name: "video"
                widget: "object"
                fields:
                  - { label: "Videolink", name: "videolink", widget: "string" }
