backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.json"
        fields:
          - label: "Galery"
            name: galery
            widget: "list"
            types:
              - label: "Image"
                name: "image"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - name: kategorie
                    label: "Filter"
                    widget: "select"
                    multiple: true
                    options: ["Filter 1", "Filter 2", "Filter 3"]
                  - name: kalenderwoche
                    label: "KW"
                    widget: "select"
                    multiple: false
                    options: ["KW 4", "KW 5", "KW 6"]
              - label: "Video"
                name: "video"
                widget: "object"
                fields:
                  - { label: "Videolink", name: "videolink", widget: "file" }
                  - name: kategorie
                    label: "Filter"
                    widget: "select"
                    multiple: true
                    options: ["Filter 1", "Filter 2", "Filter 3"]
                  - name: kalenderwoche
                    label: "KW"
                    widget: "select"
                    multiple: false
                    options: ["KW 4", "KW 5", "KW 6"]
