backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.json"
        fields:
          - label: "Wochen"
            name: week
            widget: "list"
            allow_add: true
            fields:
            - name: title
              label: "Kalenderwoche"
              widget: string
            - label: "Galery"
              name: galery
              widget: "list"
              types:
                - label: "Image"
                  name: "image"
                  widget: "object"
                  fields:
                    - { label: "Image", name: "image", widget: "image" }
                    - name: kategorie
                      label: "Kategorie"
                      widget: "select"
                      multiple: true
                      options: ["Filter 1", "Filter 2", "Filter 3"]
                - label: "Video"
                  name: "video"
                  widget: "object"
                  fields:
                    - { label: "Videolink", name: "videolink", widget: "string" }
                    - name: kategorie
                      label: "Kategorie"
                      widget: "select"
                      multiple: true
                      options: ["Filter 1", "Filter 2", "Filter 3"]
